#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-feather
Version  : 0.3.5
Release  : 46
URL      : https://cran.r-project.org/src/contrib/feather_0.3.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/feather_0.3.5.tar.gz
Summary  : R Bindings to the Feather 'API'
Group    : Development/Tools
License  : Apache-2.0
Requires: R-feather-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-hms
Requires: R-tibble
BuildRequires : R-Rcpp
BuildRequires : R-hms
BuildRequires : R-tibble
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
data store designed for maximum speed.

%package lib
Summary: lib components for the R-feather package.
Group: Libraries

%description lib
lib components for the R-feather package.


%prep
%setup -q -n feather
pushd ..
cp -a feather buildavx2
popd
pushd ..
cp -a feather buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737140981

%install
export SOURCE_DATE_EPOCH=1737140981
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/feather/DESCRIPTION
/usr/lib64/R/library/feather/INDEX
/usr/lib64/R/library/feather/Meta/Rd.rds
/usr/lib64/R/library/feather/Meta/features.rds
/usr/lib64/R/library/feather/Meta/hsearch.rds
/usr/lib64/R/library/feather/Meta/links.rds
/usr/lib64/R/library/feather/Meta/nsInfo.rds
/usr/lib64/R/library/feather/Meta/package.rds
/usr/lib64/R/library/feather/NAMESPACE
/usr/lib64/R/library/feather/NEWS.md
/usr/lib64/R/library/feather/R/feather
/usr/lib64/R/library/feather/R/feather.rdb
/usr/lib64/R/library/feather/R/feather.rdx
/usr/lib64/R/library/feather/feather/iris.feather
/usr/lib64/R/library/feather/feather/mtcars.feather
/usr/lib64/R/library/feather/help/AnIndex
/usr/lib64/R/library/feather/help/aliases.rds
/usr/lib64/R/library/feather/help/feather.rdb
/usr/lib64/R/library/feather/help/feather.rdx
/usr/lib64/R/library/feather/help/paths.rds
/usr/lib64/R/library/feather/html/00Index.html
/usr/lib64/R/library/feather/html/R.css
/usr/lib64/R/library/feather/tests/testthat.R
/usr/lib64/R/library/feather/tests/testthat/helper-roundtrip.R
/usr/lib64/R/library/feather/tests/testthat/test-class.R
/usr/lib64/R/library/feather/tests/testthat/test-overwrite.R
/usr/lib64/R/library/feather/tests/testthat/test-read.R
/usr/lib64/R/library/feather/tests/testthat/test-roundtrip-vector.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/feather/libs/feather.so
/V4/usr/lib64/R/library/feather/libs/feather.so
/usr/lib64/R/library/feather/libs/feather.so
