#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-feather
Version  : 0.3.5
Release  : 37
URL      : https://cran.r-project.org/src/contrib/feather_0.3.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/feather_0.3.5.tar.gz
Summary  : R Bindings to the Feather 'API'
Group    : Development/Tools
License  : Apache-2.0
Requires: R-feather-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-hms
Requires: R-tibble
BuildRequires : R-Rcpp
BuildRequires : R-hms
BuildRequires : R-tibble
BuildRequires : buildreq-R
BuildRequires : buildreq-cmake

%description
data store designed for maximum speed.

%package lib
Summary: lib components for the R-feather package.
Group: Libraries

%description lib
lib components for the R-feather package.


%prep
%setup -q -c -n feather
cd %{_builddir}/feather

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641014036

%install
export SOURCE_DATE_EPOCH=1641014036
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library feather
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library feather
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library feather
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc feather || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/feather/DESCRIPTION
/usr/lib64/R/library/feather/INDEX
/usr/lib64/R/library/feather/Meta/Rd.rds
/usr/lib64/R/library/feather/Meta/features.rds
/usr/lib64/R/library/feather/Meta/hsearch.rds
/usr/lib64/R/library/feather/Meta/links.rds
/usr/lib64/R/library/feather/Meta/nsInfo.rds
/usr/lib64/R/library/feather/Meta/package.rds
/usr/lib64/R/library/feather/NAMESPACE
/usr/lib64/R/library/feather/NEWS.md
/usr/lib64/R/library/feather/R/feather
/usr/lib64/R/library/feather/R/feather.rdb
/usr/lib64/R/library/feather/R/feather.rdx
/usr/lib64/R/library/feather/feather/iris.feather
/usr/lib64/R/library/feather/feather/mtcars.feather
/usr/lib64/R/library/feather/help/AnIndex
/usr/lib64/R/library/feather/help/aliases.rds
/usr/lib64/R/library/feather/help/feather.rdb
/usr/lib64/R/library/feather/help/feather.rdx
/usr/lib64/R/library/feather/help/paths.rds
/usr/lib64/R/library/feather/html/00Index.html
/usr/lib64/R/library/feather/html/R.css
/usr/lib64/R/library/feather/tests/testthat.R
/usr/lib64/R/library/feather/tests/testthat/helper-roundtrip.R
/usr/lib64/R/library/feather/tests/testthat/test-class.R
/usr/lib64/R/library/feather/tests/testthat/test-overwrite.R
/usr/lib64/R/library/feather/tests/testthat/test-read.R
/usr/lib64/R/library/feather/tests/testthat/test-roundtrip-vector.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/feather/libs/feather.so
/usr/lib64/R/library/feather/libs/feather.so.avx2
/usr/lib64/R/library/feather/libs/feather.so.avx512
